### ISSUE TITLE
Cannot use this plugin on fastify 3.x.x

### ISSUE THREAD

**Issue by bahamut657** [fastify/fastify-formbody#114]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

7.0.1 - 7.0.0

### Node.js version

16.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

ArchLinux

### Description

On task startup I obtain this error:

fastify-plugin: @fastify/formbody - expected '4.x' fastify version, '3.29.0' is installed

I think that this check is wrong (this version must be compatible with Fastify 3.xx)

### Steps to Reproduce

```
const Fastify = require("fastify");
const Formbody = require('@fastify/formbody');
const server = Fastify({
      connectionTimeout: 20 * 1000,
      logger: false
});
server.register(Formbody);
server.listen(3000,"0.0.0.0",(err,address)=>{
    if (err)
        throw err;
   else 
       console.log( "Server is active");
});
```

### Expected Behavior

Plugin works as expected using Fastify v3.xx

**Comment by Fdawgs** [comment]
Use v6.0.1, >= v7.x only supports Fastify v4 and above.

**Comment by bahamut657** [comment]
Ok It works.
Can u write  these notes on module readme please? This information is only on Release Notes
Thank you for the support
Regards

**Comment by wlinna** [comment]
I think the issue should remain open until README.md has been fixed. Right now it states the following:

> This branch targets Fastify v3. Please refer to [this branch](https://github.com/fastify/fastify-formbody/tree/3.x) and related versions for Fastify ^2.0.0 compatibility.

Nowhere does it tell which version should I use to target Fastify 3.
