### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by letto4135** [fastify/fastify-formbody#120]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### Plugin version

7.0.1

### Node.js version

16.2.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Monterey 12.4

### Description

```
Example
Given the following code:

const fastify = require('fastify')()

fastify.register(require('@fastify/formbody'))

fastify.post('/', (req, reply) => {
  reply.send(req.body)
})

fastify.listen(8000, (err) => {
  if (err) throw err
})
```

The given example fails to work with

```
AvvioError [Error]: Plugin must be a function or a promise. Received: 'object'
    at assertPlugin (*/node_modules/avvio/boot.js:207:11)
    at Boot._addPlugin (*/node_modules/avvio/boot.js:240:12)
    at Boot.use (*/node_modules/avvio/boot.js:216:25)
    at Object.server.<computed> [as register] (*/node_modules/avvio/boot.js:40:14)
    at runFastify (*/node_modules/fastify-cli/start.js:138:17)
    at async main (*/node_modules/fastify-cli/lib/watch/fork.js:40:13) {
  code: 'AVV_ERR_PLUGIN_NOT_VALID'
}
```

### Steps to Reproduce

fastify generate project
cd project
copy example code into app.js
install plugin
run

### Expected Behavior

Example code works.

Also, using fastify generate project and adding `fastify.register(require('@fastify/formbody'))` to app.js or to routes/root.js doesn't seem to work either. 
Seems like no matter where I put it in the code it doesn't work so is there an issue with using fastify generate?

**Comment by climba03003** [comment]
The example is standalone script.
It don't expect you to copy and paste and run within `fastify-cli`.

**Comment by climba03003** [comment]
Every file in plugins and routes folder should export a plugin.

Which means that you should place it on either the plugins folder and wrap the plugin with fastify-plugin. Or place it within the route that should use this plugin.


I recommend you to read the document of fastify and start it from scratch. It help you to understand the logic of how fastify works.
