### ISSUE TITLE
Does this plugin only echo the request body?

### ISSUE THREAD

**Issue by CrisLi** [fastify/fastify-formbody#2]
I try to use this plugin with the demo code in the README.md.

My testing result is that only request body echoes back, even I change the logic of my handler.

```js
fastify.register(require('fastify-formbody'), {}, (err) => {
  if (err) throw err
})

fastify.post('/', (req, reply) => {
  console.log(req.body); // not log here.
  reply.send({}) // should return an empty json, but still the content of request body.
})

fastify.listen(9001, (err) => {
  if (err) throw err;
  console.log('server listen on 9001');
});
```

**Comment by jsumners** [comment]
I need more information. What version of Fastify did you use? What request did you send (can you supply a `curl` example?)?

**Comment by CrisLi** [comment]
I am using fastify 0.37.0. The curl result is below:

```
curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=davidwalsh' -d 'password=something' http://localhost:9001
{"username":"davidwalsh","password":"something"}
```

I think there is bug under https://github.com/fastify/fastify-formbody/blob/efe60bb7e14a94a32f3039623fab02e586feb170/formbody.js#L11

The first parameter for `done` method should `null` for error.

**Comment by jsumners** [comment]
#3
