### ISSUE TITLE
npm package still pointing "fastify-formbody@3.1.0"

### ISSUE THREAD

**Issue by matth-c3** [fastify/fastify-formbody#45]
Hello, 

Following [this PR](https://github.com/fastify/fastify-formbody/pull/43), master branch includes fastify `^3.0.0-alpha.1` as devDependencies but when installing with npm ( `npm install`), it's still using fastify `2.0.0-rc.3` as devDependencies. 

As fastify v3 is not yet released as default version maybe that's on purpose. For now I just install the package directly using your repo.

Thank you.

**Comment by mcollina** [comment]
Fastify v3 is now at rc stage. You can install the fastify v3 version of this module by `npm i fastify-formbody@next`.
