### ISSUE TITLE
Use node builtin qs for parsing or add to readme noting the differences

### ISSUE THREAD

**Issue by cmawhorter** [fastify/fastify-formbody#50]
## 🚀 Feature Proposal

Fastify defaults to [using the builtin qs for parsing](https://www.fastify.io/docs/latest/Server/#querystringparser) and I expected this plugin to behave the same.  

The readme should at least call this fact out and it'd be nice if it be changed to mirror the behavior of fastify with defaulting to node built-in, but allowing optional custom parser. 

## Motivation

It's unexpected that the same data passed via querystring and this plugin would be parsed differently.  

`GET /?hello[one]=a&hello[two]=b` is transformed into `{ 'hello[one]': 'a', 'hello[two]': 'b'  }`
`POST /` with body `hello[one]=a&hello[two]=b` is transformed into `{ hello: { one: a, two: b } }`

## Example

By using the same parser, both req.query and req.body would have identical output for the same input which feels right to me.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by cmawhorter** [comment]
pr submitted. i didn't see a way to do this in a manner that wasn't a breaking change so i went that path because it also gave the benefit of one less external dep.  included tests.

**Comment by Eomm** [comment]
Released in v5

Thank you for your contribution! 🔝
