### ISSUE TITLE
Publish new patch version?

### ISSUE THREAD

**Issue by joelmukuthu** [fastify/fastify-formbody#80]
## 🚀 Feature Proposal

Not really a feature, but would you mind publishing a new version of this plugin? Particulary, to bump it's dependency on fastify-plugin from `^2.0.0` to `^3.0.0`. 

## Motivation

To remove the "fastify not found, proceeding anyway" messages in stdout that are generated by fastify-plugin version < 3.

## Example

N/A

**Comment by mcollina** [comment]
Done, thanks!
